name: PR Comment
on:
  pull_request_review:
    types: [submitted]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { owner, repo, number: issue_number } = context.issue;
            const author = context.payload.pull_request.user.login;
            if (context.payload.review.state === 'approved') {
              github.issues.createComment({
                owner,
                repo,
                issue_number,
                body: `@${author}, your PR has been approved.`
              });
            } else if (context.payload.review.state === 'changes_requested') {
              github.issues.createComment({
                owner,
                repo,
                issue_number,
                body: `@${author}, changes have been requested for your PR.`
              });
            }
