name: PR Review Requested
on:
  pull_request_review:
    types: [review_requested]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GH_TOKEN}}
          script: |
            const { owner, repo, number: issue_number } = context.issue;
            const author = context.payload.pull_request.user.login;
            const reviewers = context.payload.pull_request.requested_reviewers.map(user => '@' + user.login);

            github.issues.createComment({
              owner,
              repo,
              issue_number,
              body: `@${author} has     requested a review. Reviewers: ${reviewers.join(", ")}`
            });
